name: soscuba
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  psiphon:
    path: ../vpn_psiphon
  http: 
  dio: 
  flutter_share: ^1.0.5
  url_launcher: ^6.0.2
  easy_dynamic_theme: ^2.2.0
  path_provider: ^2.0.1
  encrypt: ^5.0.0
  toast: ^0.1.5
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.5
  image_picker: ^0.8.2



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/psiphon_config.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
